namespace CrazyMouse
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            this.listBoxY = new System.Windows.Forms.ListBox();
            this.listBoxX = new System.Windows.Forms.ListBox();
            this.domainUpDown2 = new System.Windows.Forms.DomainUpDown();
            this.labelX = new System.Windows.Forms.Label();
            this.button1 = new System.Windows.Forms.Button();
            this.labelY = new System.Windows.Forms.Label();
            this.timer1 = new System.Windows.Forms.Timer(this.components);
            this.button2 = new System.Windows.Forms.Button();
            this.textBox1 = new System.Windows.Forms.TextBox();
            this.timer2 = new System.Windows.Forms.Timer(this.components);
            this.label1 = new System.Windows.Forms.Label();
            this.checkBox1 = new System.Windows.Forms.CheckBox();
            this.SuspendLayout();
            // 
            // listBoxY
            // 
            this.listBoxY.FormattingEnabled = true;
            this.listBoxY.Location = new System.Drawing.Point(4, 7);
            this.listBoxY.Name = "listBoxY";
            this.listBoxY.Size = new System.Drawing.Size(55, 173);
            this.listBoxY.TabIndex = 0;
            // 
            // listBoxX
            // 
            this.listBoxX.FormattingEnabled = true;
            this.listBoxX.Location = new System.Drawing.Point(61, 7);
            this.listBoxX.Name = "listBoxX";
            this.listBoxX.Size = new System.Drawing.Size(55, 173);
            this.listBoxX.TabIndex = 1;
            // 
            // domainUpDown2
            // 
            this.domainUpDown2.Items.Add("1");
            this.domainUpDown2.Items.Add("10");
            this.domainUpDown2.Items.Add("20");
            this.domainUpDown2.Items.Add("30");
            this.domainUpDown2.Items.Add("40");
            this.domainUpDown2.Items.Add("50");
            this.domainUpDown2.Items.Add("60");
            this.domainUpDown2.Items.Add("70");
            this.domainUpDown2.Items.Add("80");
            this.domainUpDown2.Items.Add("90");
            this.domainUpDown2.Items.Add("100");
            this.domainUpDown2.Items.Add("110");
            this.domainUpDown2.Items.Add("120");
            this.domainUpDown2.Items.Add("130");
            this.domainUpDown2.Items.Add("140");
            this.domainUpDown2.Items.Add("150");
            this.domainUpDown2.Items.Add("160");
            this.domainUpDown2.Items.Add("170");
            this.domainUpDown2.Items.Add("180");
            this.domainUpDown2.Items.Add("190");
            this.domainUpDown2.Items.Add("200");
            this.domainUpDown2.Items.Add("210");
            this.domainUpDown2.Items.Add("220");
            this.domainUpDown2.Items.Add("230");
            this.domainUpDown2.Items.Add("240");
            this.domainUpDown2.Items.Add("250");
            this.domainUpDown2.Items.Add("260");
            this.domainUpDown2.Items.Add("270");
            this.domainUpDown2.Items.Add("280");
            this.domainUpDown2.Items.Add("290");
            this.domainUpDown2.Items.Add("300");
            this.domainUpDown2.Items.Add("310");
            this.domainUpDown2.Items.Add("320");
            this.domainUpDown2.Items.Add("330");
            this.domainUpDown2.Items.Add("340");
            this.domainUpDown2.Items.Add("350");
            this.domainUpDown2.Items.Add("360");
            this.domainUpDown2.Items.Add("370");
            this.domainUpDown2.Items.Add("380");
            this.domainUpDown2.Items.Add("390");
            this.domainUpDown2.Items.Add("400");
            this.domainUpDown2.Items.Add("410");
            this.domainUpDown2.Items.Add("420");
            this.domainUpDown2.Items.Add("430");
            this.domainUpDown2.Items.Add("440");
            this.domainUpDown2.Items.Add("450");
            this.domainUpDown2.Items.Add("460");
            this.domainUpDown2.Items.Add("470");
            this.domainUpDown2.Items.Add("480");
            this.domainUpDown2.Items.Add("490");
            this.domainUpDown2.Items.Add("500");
            this.domainUpDown2.Items.Add("510");
            this.domainUpDown2.Items.Add("520");
            this.domainUpDown2.Items.Add("530");
            this.domainUpDown2.Items.Add("540");
            this.domainUpDown2.Items.Add("550");
            this.domainUpDown2.Items.Add("560");
            this.domainUpDown2.Items.Add("570");
            this.domainUpDown2.Items.Add("580");
            this.domainUpDown2.Items.Add("590");
            this.domainUpDown2.Items.Add("600");
            this.domainUpDown2.Items.Add("610");
            this.domainUpDown2.Items.Add("620");
            this.domainUpDown2.Items.Add("630");
            this.domainUpDown2.Items.Add("640");
            this.domainUpDown2.Items.Add("650");
            this.domainUpDown2.Items.Add("660");
            this.domainUpDown2.Items.Add("670");
            this.domainUpDown2.Items.Add("680");
            this.domainUpDown2.Items.Add("690");
            this.domainUpDown2.Items.Add("700");
            this.domainUpDown2.Items.Add("710");
            this.domainUpDown2.Items.Add("720");
            this.domainUpDown2.Items.Add("730");
            this.domainUpDown2.Items.Add("740");
            this.domainUpDown2.Items.Add("750");
            this.domainUpDown2.Items.Add("760");
            this.domainUpDown2.Items.Add("770");
            this.domainUpDown2.Items.Add("780");
            this.domainUpDown2.Items.Add("790");
            this.domainUpDown2.Items.Add("800");
            this.domainUpDown2.Items.Add("810");
            this.domainUpDown2.Items.Add("820");
            this.domainUpDown2.Items.Add("830");
            this.domainUpDown2.Items.Add("840");
            this.domainUpDown2.Items.Add("850");
            this.domainUpDown2.Items.Add("860");
            this.domainUpDown2.Items.Add("870");
            this.domainUpDown2.Items.Add("880");
            this.domainUpDown2.Items.Add("890");
            this.domainUpDown2.Items.Add("900");
            this.domainUpDown2.Items.Add("910");
            this.domainUpDown2.Items.Add("920");
            this.domainUpDown2.Items.Add("930");
            this.domainUpDown2.Items.Add("940");
            this.domainUpDown2.Items.Add("950");
            this.domainUpDown2.Items.Add("960");
            this.domainUpDown2.Items.Add("970");
            this.domainUpDown2.Items.Add("980");
            this.domainUpDown2.Items.Add("990");
            this.domainUpDown2.Items.Add("1000");
            this.domainUpDown2.Items.Add("1010");
            this.domainUpDown2.Items.Add("1020");
            this.domainUpDown2.Items.Add("1030");
            this.domainUpDown2.Items.Add("1040");
            this.domainUpDown2.Items.Add("1050");
            this.domainUpDown2.Items.Add("1060");
            this.domainUpDown2.Items.Add("1070");
            this.domainUpDown2.Items.Add("1080");
            this.domainUpDown2.Items.Add("1090");
            this.domainUpDown2.Items.Add("1100");
            this.domainUpDown2.Items.Add("1110");
            this.domainUpDown2.Items.Add("1120");
            this.domainUpDown2.Items.Add("1130");
            this.domainUpDown2.Items.Add("1140");
            this.domainUpDown2.Items.Add("1150");
            this.domainUpDown2.Items.Add("1160");
            this.domainUpDown2.Items.Add("1170");
            this.domainUpDown2.Items.Add("1180");
            this.domainUpDown2.Items.Add("1190");
            this.domainUpDown2.Items.Add("1200");
            this.domainUpDown2.Items.Add("1210");
            this.domainUpDown2.Items.Add("1220");
            this.domainUpDown2.Items.Add("1230");
            this.domainUpDown2.Items.Add("1240");
            this.domainUpDown2.Items.Add("1250");
            this.domainUpDown2.Items.Add("1260");
            this.domainUpDown2.Items.Add("1270");
            this.domainUpDown2.Items.Add("1280");
            this.domainUpDown2.Items.Add("1290");
            this.domainUpDown2.Items.Add("1300");
            this.domainUpDown2.Items.Add("1310");
            this.domainUpDown2.Items.Add("1320");
            this.domainUpDown2.Items.Add("1330");
            this.domainUpDown2.Items.Add("1340");
            this.domainUpDown2.Items.Add("1350");
            this.domainUpDown2.Items.Add("1360");
            this.domainUpDown2.Items.Add("1370");
            this.domainUpDown2.Items.Add("1380");
            this.domainUpDown2.Items.Add("1390");
            this.domainUpDown2.Items.Add("1400");
            this.domainUpDown2.Items.Add("1410");
            this.domainUpDown2.Items.Add("1420");
            this.domainUpDown2.Items.Add("1430");
            this.domainUpDown2.Items.Add("1440");
            this.domainUpDown2.Items.Add("1450");
            this.domainUpDown2.Items.Add("1460");
            this.domainUpDown2.Items.Add("1470");
            this.domainUpDown2.Items.Add("1480");
            this.domainUpDown2.Items.Add("1490");
            this.domainUpDown2.Items.Add("1500");
            this.domainUpDown2.Items.Add("1510");
            this.domainUpDown2.Items.Add("1520");
            this.domainUpDown2.Items.Add("1530");
            this.domainUpDown2.Items.Add("1540");
            this.domainUpDown2.Items.Add("1550");
            this.domainUpDown2.Items.Add("1560");
            this.domainUpDown2.Items.Add("1570");
            this.domainUpDown2.Items.Add("1580");
            this.domainUpDown2.Items.Add("1590");
            this.domainUpDown2.Items.Add("1600");
            this.domainUpDown2.Items.Add("1610");
            this.domainUpDown2.Items.Add("1620");
            this.domainUpDown2.Items.Add("1630");
            this.domainUpDown2.Items.Add("1640");
            this.domainUpDown2.Items.Add("1650");
            this.domainUpDown2.Items.Add("1660");
            this.domainUpDown2.Items.Add("1670");
            this.domainUpDown2.Items.Add("1680");
            this.domainUpDown2.Items.Add("1690");
            this.domainUpDown2.Items.Add("1700");
            this.domainUpDown2.Items.Add("1710");
            this.domainUpDown2.Items.Add("1720");
            this.domainUpDown2.Items.Add("1730");
            this.domainUpDown2.Items.Add("1740");
            this.domainUpDown2.Items.Add("1750");
            this.domainUpDown2.Items.Add("1760");
            this.domainUpDown2.Items.Add("1770");
            this.domainUpDown2.Items.Add("1780");
            this.domainUpDown2.Items.Add("1790");
            this.domainUpDown2.Items.Add("1800");
            this.domainUpDown2.Items.Add("1810");
            this.domainUpDown2.Items.Add("1820");
            this.domainUpDown2.Items.Add("1830");
            this.domainUpDown2.Items.Add("1840");
            this.domainUpDown2.Items.Add("1850");
            this.domainUpDown2.Items.Add("1860");
            this.domainUpDown2.Items.Add("1870");
            this.domainUpDown2.Items.Add("1880");
            this.domainUpDown2.Items.Add("1890");
            this.domainUpDown2.Items.Add("1900");
            this.domainUpDown2.Items.Add("1910");
            this.domainUpDown2.Items.Add("1920");
            this.domainUpDown2.Items.Add("1930");
            this.domainUpDown2.Items.Add("1940");
            this.domainUpDown2.Items.Add("1950");
            this.domainUpDown2.Items.Add("1960");
            this.domainUpDown2.Items.Add("1970");
            this.domainUpDown2.Items.Add("1980");
            this.domainUpDown2.Items.Add("1990");
            this.domainUpDown2.Items.Add("2000");
            this.domainUpDown2.Items.Add("2010");
            this.domainUpDown2.Items.Add("2020");
            this.domainUpDown2.Items.Add("2030");
            this.domainUpDown2.Items.Add("2040");
            this.domainUpDown2.Items.Add("2050");
            this.domainUpDown2.Items.Add("2060");
            this.domainUpDown2.Items.Add("2070");
            this.domainUpDown2.Items.Add("2080");
            this.domainUpDown2.Items.Add("2090");
            this.domainUpDown2.Items.Add("2100");
            this.domainUpDown2.Items.Add("2110");
            this.domainUpDown2.Items.Add("2120");
            this.domainUpDown2.Items.Add("2130");
            this.domainUpDown2.Items.Add("2140");
            this.domainUpDown2.Items.Add("2150");
            this.domainUpDown2.Items.Add("2160");
            this.domainUpDown2.Items.Add("2170");
            this.domainUpDown2.Items.Add("2180");
            this.domainUpDown2.Items.Add("2190");
            this.domainUpDown2.Items.Add("2200");
            this.domainUpDown2.Items.Add("2210");
            this.domainUpDown2.Items.Add("2220");
            this.domainUpDown2.Items.Add("2230");
            this.domainUpDown2.Items.Add("2240");
            this.domainUpDown2.Items.Add("2250");
            this.domainUpDown2.Items.Add("2260");
            this.domainUpDown2.Items.Add("2270");
            this.domainUpDown2.Items.Add("2280");
            this.domainUpDown2.Items.Add("2290");
            this.domainUpDown2.Items.Add("2300");
            this.domainUpDown2.Items.Add("2310");
            this.domainUpDown2.Items.Add("2320");
            this.domainUpDown2.Items.Add("2330");
            this.domainUpDown2.Items.Add("2340");
            this.domainUpDown2.Items.Add("2350");
            this.domainUpDown2.Items.Add("2360");
            this.domainUpDown2.Items.Add("2370");
            this.domainUpDown2.Items.Add("2380");
            this.domainUpDown2.Items.Add("2390");
            this.domainUpDown2.Items.Add("2400");
            this.domainUpDown2.Items.Add("2410");
            this.domainUpDown2.Items.Add("2420");
            this.domainUpDown2.Items.Add("2430");
            this.domainUpDown2.Items.Add("2440");
            this.domainUpDown2.Items.Add("2450");
            this.domainUpDown2.Items.Add("2460");
            this.domainUpDown2.Items.Add("2470");
            this.domainUpDown2.Items.Add("2480");
            this.domainUpDown2.Items.Add("2490");
            this.domainUpDown2.Items.Add("2500");
            this.domainUpDown2.Items.Add("2510");
            this.domainUpDown2.Items.Add("2520");
            this.domainUpDown2.Items.Add("2530");
            this.domainUpDown2.Items.Add("2540");
            this.domainUpDown2.Items.Add("2550");
            this.domainUpDown2.Items.Add("2560");
            this.domainUpDown2.Items.Add("2570");
            this.domainUpDown2.Items.Add("2580");
            this.domainUpDown2.Items.Add("2590");
            this.domainUpDown2.Items.Add("2600");
            this.domainUpDown2.Items.Add("2610");
            this.domainUpDown2.Items.Add("2620");
            this.domainUpDown2.Items.Add("2630");
            this.domainUpDown2.Items.Add("2640");
            this.domainUpDown2.Items.Add("2650");
            this.domainUpDown2.Items.Add("2660");
            this.domainUpDown2.Items.Add("2670");
            this.domainUpDown2.Items.Add("2680");
            this.domainUpDown2.Items.Add("2690");
            this.domainUpDown2.Items.Add("2700");
            this.domainUpDown2.Items.Add("2710");
            this.domainUpDown2.Items.Add("2720");
            this.domainUpDown2.Items.Add("2730");
            this.domainUpDown2.Items.Add("2740");
            this.domainUpDown2.Items.Add("2750");
            this.domainUpDown2.Items.Add("2760");
            this.domainUpDown2.Items.Add("2770");
            this.domainUpDown2.Items.Add("2780");
            this.domainUpDown2.Items.Add("2790");
            this.domainUpDown2.Items.Add("2800");
            this.domainUpDown2.Items.Add("2810");
            this.domainUpDown2.Items.Add("2820");
            this.domainUpDown2.Items.Add("2830");
            this.domainUpDown2.Items.Add("2840");
            this.domainUpDown2.Items.Add("2850");
            this.domainUpDown2.Items.Add("2860");
            this.domainUpDown2.Items.Add("2870");
            this.domainUpDown2.Items.Add("2880");
            this.domainUpDown2.Items.Add("2890");
            this.domainUpDown2.Items.Add("2900");
            this.domainUpDown2.Items.Add("2910");
            this.domainUpDown2.Items.Add("2920");
            this.domainUpDown2.Items.Add("2930");
            this.domainUpDown2.Items.Add("2940");
            this.domainUpDown2.Items.Add("2950");
            this.domainUpDown2.Items.Add("2960");
            this.domainUpDown2.Items.Add("2970");
            this.domainUpDown2.Items.Add("2980");
            this.domainUpDown2.Items.Add("2990");
            this.domainUpDown2.Items.Add("3000");
            this.domainUpDown2.Items.Add("3010");
            this.domainUpDown2.Items.Add("3020");
            this.domainUpDown2.Items.Add("3030");
            this.domainUpDown2.Items.Add("3040");
            this.domainUpDown2.Items.Add("3050");
            this.domainUpDown2.Items.Add("3060");
            this.domainUpDown2.Items.Add("3070");
            this.domainUpDown2.Items.Add("3080");
            this.domainUpDown2.Items.Add("3090");
            this.domainUpDown2.Items.Add("3100");
            this.domainUpDown2.Items.Add("3110");
            this.domainUpDown2.Items.Add("3120");
            this.domainUpDown2.Items.Add("3130");
            this.domainUpDown2.Items.Add("3140");
            this.domainUpDown2.Items.Add("3150");
            this.domainUpDown2.Items.Add("3160");
            this.domainUpDown2.Items.Add("3170");
            this.domainUpDown2.Items.Add("3180");
            this.domainUpDown2.Items.Add("3190");
            this.domainUpDown2.Items.Add("3200");
            this.domainUpDown2.Items.Add("3210");
            this.domainUpDown2.Items.Add("3220");
            this.domainUpDown2.Items.Add("3230");
            this.domainUpDown2.Items.Add("3240");
            this.domainUpDown2.Items.Add("3250");
            this.domainUpDown2.Items.Add("3260");
            this.domainUpDown2.Items.Add("3270");
            this.domainUpDown2.Items.Add("3280");
            this.domainUpDown2.Items.Add("3290");
            this.domainUpDown2.Items.Add("3300");
            this.domainUpDown2.Items.Add("3310");
            this.domainUpDown2.Items.Add("3320");
            this.domainUpDown2.Items.Add("3330");
            this.domainUpDown2.Items.Add("3340");
            this.domainUpDown2.Items.Add("3350");
            this.domainUpDown2.Items.Add("3360");
            this.domainUpDown2.Items.Add("3370");
            this.domainUpDown2.Items.Add("3380");
            this.domainUpDown2.Items.Add("3390");
            this.domainUpDown2.Items.Add("3400");
            this.domainUpDown2.Items.Add("3410");
            this.domainUpDown2.Items.Add("3420");
            this.domainUpDown2.Items.Add("3430");
            this.domainUpDown2.Items.Add("3440");
            this.domainUpDown2.Items.Add("3450");
            this.domainUpDown2.Items.Add("3460");
            this.domainUpDown2.Items.Add("3470");
            this.domainUpDown2.Items.Add("3480");
            this.domainUpDown2.Items.Add("3490");
            this.domainUpDown2.Items.Add("3500");
            this.domainUpDown2.Items.Add("3510");
            this.domainUpDown2.Items.Add("3520");
            this.domainUpDown2.Items.Add("3530");
            this.domainUpDown2.Items.Add("3540");
            this.domainUpDown2.Items.Add("3550");
            this.domainUpDown2.Items.Add("3560");
            this.domainUpDown2.Items.Add("3570");
            this.domainUpDown2.Items.Add("3580");
            this.domainUpDown2.Items.Add("3590");
            this.domainUpDown2.Items.Add("3600");
            this.domainUpDown2.Items.Add("3610");
            this.domainUpDown2.Items.Add("3620");
            this.domainUpDown2.Items.Add("3630");
            this.domainUpDown2.Items.Add("3640");
            this.domainUpDown2.Items.Add("3650");
            this.domainUpDown2.Items.Add("3660");
            this.domainUpDown2.Items.Add("3670");
            this.domainUpDown2.Items.Add("3680");
            this.domainUpDown2.Items.Add("3690");
            this.domainUpDown2.Items.Add("3700");
            this.domainUpDown2.Items.Add("3710");
            this.domainUpDown2.Items.Add("3720");
            this.domainUpDown2.Items.Add("3730");
            this.domainUpDown2.Items.Add("3740");
            this.domainUpDown2.Items.Add("3750");
            this.domainUpDown2.Items.Add("3760");
            this.domainUpDown2.Items.Add("3770");
            this.domainUpDown2.Items.Add("3780");
            this.domainUpDown2.Items.Add("3790");
            this.domainUpDown2.Items.Add("3800");
            this.domainUpDown2.Items.Add("3810");
            this.domainUpDown2.Items.Add("3820");
            this.domainUpDown2.Items.Add("3830");
            this.domainUpDown2.Items.Add("3840");
            this.domainUpDown2.Items.Add("3850");
            this.domainUpDown2.Items.Add("3860");
            this.domainUpDown2.Items.Add("3870");
            this.domainUpDown2.Items.Add("3880");
            this.domainUpDown2.Items.Add("3890");
            this.domainUpDown2.Items.Add("3900");
            this.domainUpDown2.Items.Add("3910");
            this.domainUpDown2.Items.Add("3920");
            this.domainUpDown2.Items.Add("3930");
            this.domainUpDown2.Items.Add("3940");
            this.domainUpDown2.Items.Add("3950");
            this.domainUpDown2.Items.Add("3960");
            this.domainUpDown2.Items.Add("3970");
            this.domainUpDown2.Items.Add("3980");
            this.domainUpDown2.Items.Add("3990");
            this.domainUpDown2.Items.Add("4000");
            this.domainUpDown2.Items.Add("4010");
            this.domainUpDown2.Items.Add("4020");
            this.domainUpDown2.Items.Add("4030");
            this.domainUpDown2.Items.Add("4040");
            this.domainUpDown2.Items.Add("4050");
            this.domainUpDown2.Items.Add("4060");
            this.domainUpDown2.Items.Add("4070");
            this.domainUpDown2.Items.Add("4080");
            this.domainUpDown2.Items.Add("4090");
            this.domainUpDown2.Items.Add("4100");
            this.domainUpDown2.Items.Add("4110");
            this.domainUpDown2.Items.Add("4120");
            this.domainUpDown2.Items.Add("4130");
            this.domainUpDown2.Items.Add("4140");
            this.domainUpDown2.Items.Add("4150");
            this.domainUpDown2.Items.Add("4160");
            this.domainUpDown2.Items.Add("4170");
            this.domainUpDown2.Items.Add("4180");
            this.domainUpDown2.Items.Add("4190");
            this.domainUpDown2.Items.Add("4200");
            this.domainUpDown2.Items.Add("4210");
            this.domainUpDown2.Items.Add("4220");
            this.domainUpDown2.Items.Add("4230");
            this.domainUpDown2.Items.Add("4240");
            this.domainUpDown2.Items.Add("4250");
            this.domainUpDown2.Items.Add("4260");
            this.domainUpDown2.Items.Add("4270");
            this.domainUpDown2.Items.Add("4280");
            this.domainUpDown2.Items.Add("4290");
            this.domainUpDown2.Items.Add("4300");
            this.domainUpDown2.Items.Add("4310");
            this.domainUpDown2.Items.Add("4320");
            this.domainUpDown2.Items.Add("4330");
            this.domainUpDown2.Items.Add("4340");
            this.domainUpDown2.Items.Add("4350");
            this.domainUpDown2.Items.Add("4360");
            this.domainUpDown2.Items.Add("4370");
            this.domainUpDown2.Items.Add("4380");
            this.domainUpDown2.Items.Add("4390");
            this.domainUpDown2.Items.Add("4400");
            this.domainUpDown2.Items.Add("4410");
            this.domainUpDown2.Items.Add("4420");
            this.domainUpDown2.Items.Add("4430");
            this.domainUpDown2.Items.Add("4440");
            this.domainUpDown2.Items.Add("4450");
            this.domainUpDown2.Items.Add("4460");
            this.domainUpDown2.Items.Add("4470");
            this.domainUpDown2.Items.Add("4480");
            this.domainUpDown2.Items.Add("4490");
            this.domainUpDown2.Items.Add("4500");
            this.domainUpDown2.Items.Add("4510");
            this.domainUpDown2.Items.Add("4520");
            this.domainUpDown2.Items.Add("4530");
            this.domainUpDown2.Items.Add("4540");
            this.domainUpDown2.Items.Add("4550");
            this.domainUpDown2.Items.Add("4560");
            this.domainUpDown2.Items.Add("4570");
            this.domainUpDown2.Items.Add("4580");
            this.domainUpDown2.Items.Add("4590");
            this.domainUpDown2.Items.Add("4600");
            this.domainUpDown2.Items.Add("4610");
            this.domainUpDown2.Items.Add("4620");
            this.domainUpDown2.Items.Add("4630");
            this.domainUpDown2.Items.Add("4640");
            this.domainUpDown2.Items.Add("4650");
            this.domainUpDown2.Items.Add("4660");
            this.domainUpDown2.Items.Add("4670");
            this.domainUpDown2.Items.Add("4680");
            this.domainUpDown2.Items.Add("4690");
            this.domainUpDown2.Items.Add("4700");
            this.domainUpDown2.Items.Add("4710");
            this.domainUpDown2.Items.Add("4720");
            this.domainUpDown2.Items.Add("4730");
            this.domainUpDown2.Items.Add("4740");
            this.domainUpDown2.Items.Add("4750");
            this.domainUpDown2.Items.Add("4760");
            this.domainUpDown2.Items.Add("4770");
            this.domainUpDown2.Items.Add("4780");
            this.domainUpDown2.Items.Add("4790");
            this.domainUpDown2.Items.Add("4800");
            this.domainUpDown2.Items.Add("4810");
            this.domainUpDown2.Items.Add("4820");
            this.domainUpDown2.Items.Add("4830");
            this.domainUpDown2.Items.Add("4840");
            this.domainUpDown2.Items.Add("4850");
            this.domainUpDown2.Items.Add("4860");
            this.domainUpDown2.Items.Add("4870");
            this.domainUpDown2.Items.Add("4880");
            this.domainUpDown2.Items.Add("4890");
            this.domainUpDown2.Items.Add("4900");
            this.domainUpDown2.Items.Add("4910");
            this.domainUpDown2.Items.Add("4920");
            this.domainUpDown2.Items.Add("4930");
            this.domainUpDown2.Items.Add("4940");
            this.domainUpDown2.Items.Add("4950");
            this.domainUpDown2.Items.Add("4960");
            this.domainUpDown2.Items.Add("4970");
            this.domainUpDown2.Items.Add("4980");
            this.domainUpDown2.Items.Add("4990");
            this.domainUpDown2.Items.Add("5000");
            this.domainUpDown2.Items.Add("5010");
            this.domainUpDown2.Items.Add("5020");
            this.domainUpDown2.Items.Add("5030");
            this.domainUpDown2.Items.Add("5040");
            this.domainUpDown2.Items.Add("5050");
            this.domainUpDown2.Items.Add("5060");
            this.domainUpDown2.Items.Add("5070");
            this.domainUpDown2.Items.Add("5080");
            this.domainUpDown2.Items.Add("5090");
            this.domainUpDown2.Items.Add("5100");
            this.domainUpDown2.Items.Add("5110");
            this.domainUpDown2.Items.Add("5120");
            this.domainUpDown2.Items.Add("5130");
            this.domainUpDown2.Items.Add("5140");
            this.domainUpDown2.Items.Add("5150");
            this.domainUpDown2.Items.Add("5160");
            this.domainUpDown2.Items.Add("5170");
            this.domainUpDown2.Items.Add("5180");
            this.domainUpDown2.Items.Add("5190");
            this.domainUpDown2.Items.Add("5200");
            this.domainUpDown2.Items.Add("5210");
            this.domainUpDown2.Items.Add("5220");
            this.domainUpDown2.Items.Add("5230");
            this.domainUpDown2.Items.Add("5240");
            this.domainUpDown2.Items.Add("5250");
            this.domainUpDown2.Items.Add("5260");
            this.domainUpDown2.Items.Add("5270");
            this.domainUpDown2.Items.Add("5280");
            this.domainUpDown2.Items.Add("5290");
            this.domainUpDown2.Items.Add("5300");
            this.domainUpDown2.Items.Add("5310");
            this.domainUpDown2.Items.Add("5320");
            this.domainUpDown2.Items.Add("5330");
            this.domainUpDown2.Items.Add("5340");
            this.domainUpDown2.Items.Add("5350");
            this.domainUpDown2.Items.Add("5360");
            this.domainUpDown2.Items.Add("5370");
            this.domainUpDown2.Items.Add("5380");
            this.domainUpDown2.Items.Add("5390");
            this.domainUpDown2.Items.Add("5400");
            this.domainUpDown2.Items.Add("5410");
            this.domainUpDown2.Items.Add("5420");
            this.domainUpDown2.Items.Add("5430");
            this.domainUpDown2.Items.Add("5440");
            this.domainUpDown2.Items.Add("5450");
            this.domainUpDown2.Items.Add("5460");
            this.domainUpDown2.Items.Add("5470");
            this.domainUpDown2.Items.Add("5480");
            this.domainUpDown2.Items.Add("5490");
            this.domainUpDown2.Items.Add("5500");
            this.domainUpDown2.Items.Add("5510");
            this.domainUpDown2.Items.Add("5520");
            this.domainUpDown2.Items.Add("5530");
            this.domainUpDown2.Items.Add("5540");
            this.domainUpDown2.Items.Add("5550");
            this.domainUpDown2.Items.Add("5560");
            this.domainUpDown2.Items.Add("5570");
            this.domainUpDown2.Items.Add("5580");
            this.domainUpDown2.Items.Add("5590");
            this.domainUpDown2.Items.Add("5600");
            this.domainUpDown2.Items.Add("5610");
            this.domainUpDown2.Items.Add("5620");
            this.domainUpDown2.Items.Add("5630");
            this.domainUpDown2.Items.Add("5640");
            this.domainUpDown2.Items.Add("5650");
            this.domainUpDown2.Items.Add("5660");
            this.domainUpDown2.Items.Add("5670");
            this.domainUpDown2.Items.Add("5680");
            this.domainUpDown2.Items.Add("5690");
            this.domainUpDown2.Items.Add("5700");
            this.domainUpDown2.Items.Add("5710");
            this.domainUpDown2.Items.Add("5720");
            this.domainUpDown2.Items.Add("5730");
            this.domainUpDown2.Items.Add("5740");
            this.domainUpDown2.Items.Add("5750");
            this.domainUpDown2.Items.Add("5760");
            this.domainUpDown2.Items.Add("5770");
            this.domainUpDown2.Items.Add("5780");
            this.domainUpDown2.Items.Add("5790");
            this.domainUpDown2.Items.Add("5800");
            this.domainUpDown2.Items.Add("5810");
            this.domainUpDown2.Items.Add("5820");
            this.domainUpDown2.Items.Add("5830");
            this.domainUpDown2.Items.Add("5840");
            this.domainUpDown2.Items.Add("5850");
            this.domainUpDown2.Items.Add("5860");
            this.domainUpDown2.Items.Add("5870");
            this.domainUpDown2.Items.Add("5880");
            this.domainUpDown2.Items.Add("5890");
            this.domainUpDown2.Items.Add("5900");
            this.domainUpDown2.Items.Add("5910");
            this.domainUpDown2.Items.Add("5920");
            this.domainUpDown2.Items.Add("5930");
            this.domainUpDown2.Items.Add("5940");
            this.domainUpDown2.Items.Add("5950");
            this.domainUpDown2.Items.Add("5960");
            this.domainUpDown2.Items.Add("5970");
            this.domainUpDown2.Items.Add("5980");
            this.domainUpDown2.Items.Add("5990");
            this.domainUpDown2.Items.Add("6000");
            this.domainUpDown2.Items.Add("6010");
            this.domainUpDown2.Items.Add("6020");
            this.domainUpDown2.Items.Add("6030");
            this.domainUpDown2.Items.Add("6040");
            this.domainUpDown2.Items.Add("6050");
            this.domainUpDown2.Items.Add("6060");
            this.domainUpDown2.Items.Add("6070");
            this.domainUpDown2.Items.Add("6080");
            this.domainUpDown2.Items.Add("6090");
            this.domainUpDown2.Items.Add("6100");
            this.domainUpDown2.Items.Add("6110");
            this.domainUpDown2.Items.Add("6120");
            this.domainUpDown2.Items.Add("6130");
            this.domainUpDown2.Items.Add("6140");
            this.domainUpDown2.Items.Add("6150");
            this.domainUpDown2.Items.Add("6160");
            this.domainUpDown2.Items.Add("6170");
            this.domainUpDown2.Items.Add("6180");
            this.domainUpDown2.Items.Add("6190");
            this.domainUpDown2.Items.Add("6200");
            this.domainUpDown2.Items.Add("6210");
            this.domainUpDown2.Items.Add("6220");
            this.domainUpDown2.Items.Add("6230");
            this.domainUpDown2.Items.Add("6240");
            this.domainUpDown2.Items.Add("6250");
            this.domainUpDown2.Items.Add("6260");
            this.domainUpDown2.Items.Add("6270");
            this.domainUpDown2.Items.Add("6280");
            this.domainUpDown2.Items.Add("6290");
            this.domainUpDown2.Items.Add("6300");
            this.domainUpDown2.Items.Add("6310");
            this.domainUpDown2.Items.Add("6320");
            this.domainUpDown2.Items.Add("6330");
            this.domainUpDown2.Items.Add("6340");
            this.domainUpDown2.Items.Add("6350");
            this.domainUpDown2.Items.Add("6360");
            this.domainUpDown2.Items.Add("6370");
            this.domainUpDown2.Items.Add("6380");
            this.domainUpDown2.Items.Add("6390");
            this.domainUpDown2.Items.Add("6400");
            this.domainUpDown2.Items.Add("6410");
            this.domainUpDown2.Items.Add("6420");
            this.domainUpDown2.Items.Add("6430");
            this.domainUpDown2.Items.Add("6440");
            this.domainUpDown2.Items.Add("6450");
            this.domainUpDown2.Items.Add("6460");
            this.domainUpDown2.Items.Add("6470");
            this.domainUpDown2.Items.Add("6480");
            this.domainUpDown2.Items.Add("6490");
            this.domainUpDown2.Items.Add("6500");
            this.domainUpDown2.Items.Add("6510");
            this.domainUpDown2.Items.Add("6520");
            this.domainUpDown2.Items.Add("6530");
            this.domainUpDown2.Items.Add("6540");
            this.domainUpDown2.Items.Add("6550");
            this.domainUpDown2.Items.Add("6560");
            this.domainUpDown2.Items.Add("6570");
            this.domainUpDown2.Items.Add("6580");
            this.domainUpDown2.Items.Add("6590");
            this.domainUpDown2.Items.Add("6600");
            this.domainUpDown2.Items.Add("6610");
            this.domainUpDown2.Items.Add("6620");
            this.domainUpDown2.Items.Add("6630");
            this.domainUpDown2.Items.Add("6640");
            this.domainUpDown2.Items.Add("6650");
            this.domainUpDown2.Items.Add("6660");
            this.domainUpDown2.Items.Add("6670");
            this.domainUpDown2.Items.Add("6680");
            this.domainUpDown2.Items.Add("6690");
            this.domainUpDown2.Items.Add("6700");
            this.domainUpDown2.Items.Add("6710");
            this.domainUpDown2.Items.Add("6720");
            this.domainUpDown2.Items.Add("6730");
            this.domainUpDown2.Items.Add("6740");
            this.domainUpDown2.Items.Add("6750");
            this.domainUpDown2.Items.Add("6760");
            this.domainUpDown2.Items.Add("6770");
            this.domainUpDown2.Items.Add("6780");
            this.domainUpDown2.Items.Add("6790");
            this.domainUpDown2.Items.Add("6800");
            this.domainUpDown2.Items.Add("6810");
            this.domainUpDown2.Items.Add("6820");
            this.domainUpDown2.Items.Add("6830");
            this.domainUpDown2.Items.Add("6840");
            this.domainUpDown2.Items.Add("6850");
            this.domainUpDown2.Items.Add("6860");
            this.domainUpDown2.Items.Add("6870");
            this.domainUpDown2.Items.Add("6880");
            this.domainUpDown2.Items.Add("6890");
            this.domainUpDown2.Items.Add("6900");
            this.domainUpDown2.Items.Add("6910");
            this.domainUpDown2.Items.Add("6920");
            this.domainUpDown2.Items.Add("6930");
            this.domainUpDown2.Items.Add("6940");
            this.domainUpDown2.Items.Add("6950");
            this.domainUpDown2.Items.Add("6960");
            this.domainUpDown2.Items.Add("6970");
            this.domainUpDown2.Items.Add("6980");
            this.domainUpDown2.Items.Add("6990");
            this.domainUpDown2.Items.Add("7000");
            this.domainUpDown2.Items.Add("7010");
            this.domainUpDown2.Items.Add("7020");
            this.domainUpDown2.Items.Add("7030");
            this.domainUpDown2.Items.Add("7040");
            this.domainUpDown2.Items.Add("7050");
            this.domainUpDown2.Items.Add("7060");
            this.domainUpDown2.Items.Add("7070");
            this.domainUpDown2.Items.Add("7080");
            this.domainUpDown2.Items.Add("7090");
            this.domainUpDown2.Items.Add("7100");
            this.domainUpDown2.Items.Add("7110");
            this.domainUpDown2.Items.Add("7120");
            this.domainUpDown2.Items.Add("7130");
            this.domainUpDown2.Items.Add("7140");
            this.domainUpDown2.Items.Add("7150");
            this.domainUpDown2.Items.Add("7160");
            this.domainUpDown2.Items.Add("7170");
            this.domainUpDown2.Items.Add("7180");
            this.domainUpDown2.Items.Add("7190");
            this.domainUpDown2.Items.Add("7200");
            this.domainUpDown2.Items.Add("7210");
            this.domainUpDown2.Items.Add("7220");
            this.domainUpDown2.Items.Add("7230");
            this.domainUpDown2.Items.Add("7240");
            this.domainUpDown2.Items.Add("7250");
            this.domainUpDown2.Items.Add("7260");
            this.domainUpDown2.Items.Add("7270");
            this.domainUpDown2.Items.Add("7280");
            this.domainUpDown2.Items.Add("7290");
            this.domainUpDown2.Items.Add("7300");
            this.domainUpDown2.Items.Add("7310");
            this.domainUpDown2.Items.Add("7320");
            this.domainUpDown2.Items.Add("7330");
            this.domainUpDown2.Items.Add("7340");
            this.domainUpDown2.Items.Add("7350");
            this.domainUpDown2.Items.Add("7360");
            this.domainUpDown2.Items.Add("7370");
            this.domainUpDown2.Items.Add("7380");
            this.domainUpDown2.Items.Add("7390");
            this.domainUpDown2.Items.Add("7400");
            this.domainUpDown2.Items.Add("7410");
            this.domainUpDown2.Items.Add("7420");
            this.domainUpDown2.Items.Add("7430");
            this.domainUpDown2.Items.Add("7440");
            this.domainUpDown2.Items.Add("7450");
            this.domainUpDown2.Items.Add("7460");
            this.domainUpDown2.Items.Add("7470");
            this.domainUpDown2.Items.Add("7480");
            this.domainUpDown2.Items.Add("7490");
            this.domainUpDown2.Items.Add("7500");
            this.domainUpDown2.Items.Add("7510");
            this.domainUpDown2.Items.Add("7520");
            this.domainUpDown2.Items.Add("7530");
            this.domainUpDown2.Items.Add("7540");
            this.domainUpDown2.Items.Add("7550");
            this.domainUpDown2.Items.Add("7560");
            this.domainUpDown2.Items.Add("7570");
            this.domainUpDown2.Items.Add("7580");
            this.domainUpDown2.Items.Add("7590");
            this.domainUpDown2.Items.Add("7600");
            this.domainUpDown2.Items.Add("7610");
            this.domainUpDown2.Items.Add("7620");
            this.domainUpDown2.Items.Add("7630");
            this.domainUpDown2.Items.Add("7640");
            this.domainUpDown2.Items.Add("7650");
            this.domainUpDown2.Items.Add("7660");
            this.domainUpDown2.Items.Add("7670");
            this.domainUpDown2.Items.Add("7680");
            this.domainUpDown2.Items.Add("7690");
            this.domainUpDown2.Items.Add("7700");
            this.domainUpDown2.Items.Add("7710");
            this.domainUpDown2.Items.Add("7720");
            this.domainUpDown2.Items.Add("7730");
            this.domainUpDown2.Items.Add("7740");
            this.domainUpDown2.Items.Add("7750");
            this.domainUpDown2.Items.Add("7760");
            this.domainUpDown2.Items.Add("7770");
            this.domainUpDown2.Items.Add("7780");
            this.domainUpDown2.Items.Add("7790");
            this.domainUpDown2.Items.Add("7800");
            this.domainUpDown2.Items.Add("7810");
            this.domainUpDown2.Items.Add("7820");
            this.domainUpDown2.Items.Add("7830");
            this.domainUpDown2.Items.Add("7840");
            this.domainUpDown2.Items.Add("7850");
            this.domainUpDown2.Items.Add("7860");
            this.domainUpDown2.Items.Add("7870");
            this.domainUpDown2.Items.Add("7880");
            this.domainUpDown2.Items.Add("7890");
            this.domainUpDown2.Items.Add("7900");
            this.domainUpDown2.Items.Add("7910");
            this.domainUpDown2.Items.Add("7920");
            this.domainUpDown2.Items.Add("7930");
            this.domainUpDown2.Items.Add("7940");
            this.domainUpDown2.Items.Add("7950");
            this.domainUpDown2.Items.Add("7960");
            this.domainUpDown2.Items.Add("7970");
            this.domainUpDown2.Items.Add("7980");
            this.domainUpDown2.Items.Add("7990");
            this.domainUpDown2.Items.Add("8000");
            this.domainUpDown2.Items.Add("8010");
            this.domainUpDown2.Items.Add("8020");
            this.domainUpDown2.Items.Add("8030");
            this.domainUpDown2.Items.Add("8040");
            this.domainUpDown2.Items.Add("8050");
            this.domainUpDown2.Items.Add("8060");
            this.domainUpDown2.Items.Add("8070");
            this.domainUpDown2.Items.Add("8080");
            this.domainUpDown2.Items.Add("8090");
            this.domainUpDown2.Items.Add("8100");
            this.domainUpDown2.Items.Add("8110");
            this.domainUpDown2.Items.Add("8120");
            this.domainUpDown2.Items.Add("8130");
            this.domainUpDown2.Items.Add("8140");
            this.domainUpDown2.Items.Add("8150");
            this.domainUpDown2.Items.Add("8160");
            this.domainUpDown2.Items.Add("8170");
            this.domainUpDown2.Items.Add("8180");
            this.domainUpDown2.Items.Add("8190");
            this.domainUpDown2.Items.Add("8200");
            this.domainUpDown2.Items.Add("8210");
            this.domainUpDown2.Items.Add("8220");
            this.domainUpDown2.Items.Add("8230");
            this.domainUpDown2.Items.Add("8240");
            this.domainUpDown2.Items.Add("8250");
            this.domainUpDown2.Items.Add("8260");
            this.domainUpDown2.Items.Add("8270");
            this.domainUpDown2.Items.Add("8280");
            this.domainUpDown2.Items.Add("8290");
            this.domainUpDown2.Items.Add("8300");
            this.domainUpDown2.Items.Add("8310");
            this.domainUpDown2.Items.Add("8320");
            this.domainUpDown2.Items.Add("8330");
            this.domainUpDown2.Items.Add("8340");
            this.domainUpDown2.Items.Add("8350");
            this.domainUpDown2.Items.Add("8360");
            this.domainUpDown2.Items.Add("8370");
            this.domainUpDown2.Items.Add("8380");
            this.domainUpDown2.Items.Add("8390");
            this.domainUpDown2.Items.Add("8400");
            this.domainUpDown2.Items.Add("8410");
            this.domainUpDown2.Items.Add("8420");
            this.domainUpDown2.Items.Add("8430");
            this.domainUpDown2.Items.Add("8440");
            this.domainUpDown2.Items.Add("8450");
            this.domainUpDown2.Items.Add("8460");
            this.domainUpDown2.Items.Add("8470");
            this.domainUpDown2.Items.Add("8480");
            this.domainUpDown2.Items.Add("8490");
            this.domainUpDown2.Items.Add("8500");
            this.domainUpDown2.Items.Add("8510");
            this.domainUpDown2.Items.Add("8520");
            this.domainUpDown2.Items.Add("8530");
            this.domainUpDown2.Items.Add("8540");
            this.domainUpDown2.Items.Add("8550");
            this.domainUpDown2.Items.Add("8560");
            this.domainUpDown2.Items.Add("8570");
            this.domainUpDown2.Items.Add("8580");
            this.domainUpDown2.Items.Add("8590");
            this.domainUpDown2.Items.Add("8600");
            this.domainUpDown2.Items.Add("8610");
            this.domainUpDown2.Items.Add("8620");
            this.domainUpDown2.Items.Add("8630");
            this.domainUpDown2.Items.Add("8640");
            this.domainUpDown2.Items.Add("8650");
            this.domainUpDown2.Items.Add("8660");
            this.domainUpDown2.Items.Add("8670");
            this.domainUpDown2.Items.Add("8680");
            this.domainUpDown2.Items.Add("8690");
            this.domainUpDown2.Items.Add("8700");
            this.domainUpDown2.Items.Add("8710");
            this.domainUpDown2.Items.Add("8720");
            this.domainUpDown2.Items.Add("8730");
            this.domainUpDown2.Items.Add("8740");
            this.domainUpDown2.Items.Add("8750");
            this.domainUpDown2.Items.Add("8760");
            this.domainUpDown2.Items.Add("8770");
            this.domainUpDown2.Items.Add("8780");
            this.domainUpDown2.Items.Add("8790");
            this.domainUpDown2.Items.Add("8800");
            this.domainUpDown2.Items.Add("8810");
            this.domainUpDown2.Items.Add("8820");
            this.domainUpDown2.Items.Add("8830");
            this.domainUpDown2.Items.Add("8840");
            this.domainUpDown2.Items.Add("8850");
            this.domainUpDown2.Items.Add("8860");
            this.domainUpDown2.Items.Add("8870");
            this.domainUpDown2.Items.Add("8880");
            this.domainUpDown2.Items.Add("8890");
            this.domainUpDown2.Items.Add("8900");
            this.domainUpDown2.Items.Add("8910");
            this.domainUpDown2.Items.Add("8920");
            this.domainUpDown2.Items.Add("8930");
            this.domainUpDown2.Items.Add("8940");
            this.domainUpDown2.Items.Add("8950");
            this.domainUpDown2.Items.Add("8960");
            this.domainUpDown2.Items.Add("8970");
            this.domainUpDown2.Items.Add("8980");
            this.domainUpDown2.Items.Add("8990");
            this.domainUpDown2.Items.Add("9000");
            this.domainUpDown2.Items.Add("9010");
            this.domainUpDown2.Items.Add("9020");
            this.domainUpDown2.Items.Add("9030");
            this.domainUpDown2.Items.Add("9040");
            this.domainUpDown2.Items.Add("9050");
            this.domainUpDown2.Items.Add("9060");
            this.domainUpDown2.Items.Add("9070");
            this.domainUpDown2.Items.Add("9080");
            this.domainUpDown2.Items.Add("9090");
            this.domainUpDown2.Items.Add("9100");
            this.domainUpDown2.Items.Add("9110");
            this.domainUpDown2.Items.Add("9120");
            this.domainUpDown2.Items.Add("9130");
            this.domainUpDown2.Items.Add("9140");
            this.domainUpDown2.Items.Add("9150");
            this.domainUpDown2.Items.Add("9160");
            this.domainUpDown2.Items.Add("9170");
            this.domainUpDown2.Items.Add("9180");
            this.domainUpDown2.Items.Add("9190");
            this.domainUpDown2.Items.Add("9200");
            this.domainUpDown2.Items.Add("9210");
            this.domainUpDown2.Items.Add("9220");
            this.domainUpDown2.Items.Add("9230");
            this.domainUpDown2.Items.Add("9240");
            this.domainUpDown2.Items.Add("9250");
            this.domainUpDown2.Items.Add("9260");
            this.domainUpDown2.Items.Add("9270");
            this.domainUpDown2.Items.Add("9280");
            this.domainUpDown2.Items.Add("9290");
            this.domainUpDown2.Items.Add("9300");
            this.domainUpDown2.Items.Add("9310");
            this.domainUpDown2.Items.Add("9320");
            this.domainUpDown2.Items.Add("9330");
            this.domainUpDown2.Items.Add("9340");
            this.domainUpDown2.Items.Add("9350");
            this.domainUpDown2.Items.Add("9360");
            this.domainUpDown2.Items.Add("9370");
            this.domainUpDown2.Items.Add("9380");
            this.domainUpDown2.Items.Add("9390");
            this.domainUpDown2.Items.Add("9400");
            this.domainUpDown2.Items.Add("9410");
            this.domainUpDown2.Items.Add("9420");
            this.domainUpDown2.Items.Add("9430");
            this.domainUpDown2.Items.Add("9440");
            this.domainUpDown2.Items.Add("9450");
            this.domainUpDown2.Items.Add("9460");
            this.domainUpDown2.Items.Add("9470");
            this.domainUpDown2.Items.Add("9480");
            this.domainUpDown2.Items.Add("9490");
            this.domainUpDown2.Items.Add("9500");
            this.domainUpDown2.Items.Add("9510");
            this.domainUpDown2.Items.Add("9520");
            this.domainUpDown2.Items.Add("9530");
            this.domainUpDown2.Items.Add("9540");
            this.domainUpDown2.Items.Add("9550");
            this.domainUpDown2.Items.Add("9560");
            this.domainUpDown2.Items.Add("9570");
            this.domainUpDown2.Items.Add("9580");
            this.domainUpDown2.Items.Add("9590");
            this.domainUpDown2.Items.Add("9600");
            this.domainUpDown2.Items.Add("9610");
            this.domainUpDown2.Items.Add("9620");
            this.domainUpDown2.Items.Add("9630");
            this.domainUpDown2.Items.Add("9640");
            this.domainUpDown2.Items.Add("9650");
            this.domainUpDown2.Items.Add("9660");
            this.domainUpDown2.Items.Add("9670");
            this.domainUpDown2.Items.Add("9680");
            this.domainUpDown2.Items.Add("9690");
            this.domainUpDown2.Items.Add("9700");
            this.domainUpDown2.Items.Add("9710");
            this.domainUpDown2.Items.Add("9720");
            this.domainUpDown2.Items.Add("9730");
            this.domainUpDown2.Items.Add("9740");
            this.domainUpDown2.Items.Add("9750");
            this.domainUpDown2.Items.Add("9760");
            this.domainUpDown2.Items.Add("9770");
            this.domainUpDown2.Items.Add("9780");
            this.domainUpDown2.Items.Add("9790");
            this.domainUpDown2.Items.Add("9800");
            this.domainUpDown2.Items.Add("9810");
            this.domainUpDown2.Items.Add("9820");
            this.domainUpDown2.Items.Add("9830");
            this.domainUpDown2.Items.Add("9840");
            this.domainUpDown2.Items.Add("9850");
            this.domainUpDown2.Items.Add("9860");
            this.domainUpDown2.Items.Add("9870");
            this.domainUpDown2.Items.Add("9880");
            this.domainUpDown2.Items.Add("9890");
            this.domainUpDown2.Items.Add("9900");
            this.domainUpDown2.Items.Add("9910");
            this.domainUpDown2.Items.Add("9920");
            this.domainUpDown2.Items.Add("9930");
            this.domainUpDown2.Items.Add("9940");
            this.domainUpDown2.Items.Add("9950");
            this.domainUpDown2.Items.Add("9960");
            this.domainUpDown2.Items.Add("9970");
            this.domainUpDown2.Items.Add("9980");
            this.domainUpDown2.Items.Add("9990");
            this.domainUpDown2.Items.Add("9999");
            this.domainUpDown2.Location = new System.Drawing.Point(163, 7);
            this.domainUpDown2.Name = "domainUpDown2";
            this.domainUpDown2.ReadOnly = true;
            this.domainUpDown2.Size = new System.Drawing.Size(52, 20);
            this.domainUpDown2.TabIndex = 3;
            this.domainUpDown2.Text = "10";
            // 
            // labelX
            // 
            this.labelX.AutoSize = true;
            this.labelX.Location = new System.Drawing.Point(122, 117);
            this.labelX.Name = "labelX";
            this.labelX.Size = new System.Drawing.Size(35, 13);
            this.labelX.TabIndex = 4;
            this.labelX.Text = "label1";
            // 
            // button1
            // 
            this.button1.Location = new System.Drawing.Point(122, 157);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(46, 23);
            this.button1.TabIndex = 5;
            this.button1.Text = "Reset";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // labelY
            // 
            this.labelY.AutoSize = true;
            this.labelY.Location = new System.Drawing.Point(163, 117);
            this.labelY.Name = "labelY";
            this.labelY.Size = new System.Drawing.Size(35, 13);
            this.labelY.TabIndex = 6;
            this.labelY.Text = "label2";
            // 
            // timer1
            // 
            this.timer1.Tick += new System.EventHandler(this.timer1_Tick);
            // 
            // button2
            // 
            this.button2.Location = new System.Drawing.Point(174, 157);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(41, 23);
            this.button2.TabIndex = 7;
            this.button2.Text = "Help";
            this.button2.UseVisualStyleBackColor = true;
            this.button2.Click += new System.EventHandler(this.button2_Click);
            // 
            // textBox1
            // 
            this.textBox1.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.textBox1.Location = new System.Drawing.Point(122, 7);
            this.textBox1.MaxLength = 4;
            this.textBox1.Name = "textBox1";
            this.textBox1.Size = new System.Drawing.Size(35, 20);
            this.textBox1.TabIndex = 8;
            this.textBox1.Text = "1";
            this.textBox1.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.textBox1_KeyPress);
            // 
            // timer2
            // 
            this.timer2.Tick += new System.EventHandler(this.timerCursorClick_Tick);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(122, 34);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(13, 13);
            this.label1.TabIndex = 9;
            this.label1.Text = "0";
            // 
            // checkBox1
            // 
            this.checkBox1.AutoSize = true;
            this.checkBox1.Location = new System.Drawing.Point(122, 50);
            this.checkBox1.Name = "checkBox1";
            this.checkBox1.Size = new System.Drawing.Size(92, 17);
            this.checkBox1.TabIndex = 10;
            this.checkBox1.Text = "Endless Cycle";
            this.checkBox1.UseVisualStyleBackColor = true;
            this.checkBox1.CheckedChanged += new System.EventHandler(this.checkBox1_CheckedChanged);
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(218, 184);
            this.Controls.Add(this.checkBox1);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.textBox1);
            this.Controls.Add(this.button2);
            this.Controls.Add(this.labelY);
            this.Controls.Add(this.button1);
            this.Controls.Add(this.labelX);
            this.Controls.Add(this.domainUpDown2);
            this.Controls.Add(this.listBoxX);
            this.Controls.Add(this.listBoxY);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.KeyPreview = true;
            this.MaximumSize = new System.Drawing.Size(234, 223);
            this.MinimumSize = new System.Drawing.Size(234, 223);
            this.Name = "Form1";
            this.StartPosition = System.Windows.Forms.FormStartPosition.WindowsDefaultBounds;
            this.Text = "Crazy Mouse";
            this.TopMost = true;
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.ListBox listBoxY;
        private System.Windows.Forms.ListBox listBoxX;
        private System.Windows.Forms.DomainUpDown domainUpDown2;
        private System.Windows.Forms.Label labelX;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.Label labelY;
        private System.Windows.Forms.Timer timer1;
        private System.Windows.Forms.Button button2;
        private System.Windows.Forms.TextBox textBox1;
        private System.Windows.Forms.Timer timer2;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.CheckBox checkBox1;
    }
}

